
name: Run Traffic Command with Playwright and xvfb

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main # Run workflow on push to the 'main' branch

jobs:
  run-traffic-command:
    runs-on: ubuntu-latest

    env:
      PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
      PROXY_PORT: ${{ secrets.PROXY_PORT }}
      PROXY_SERVER: ${{ secrets.PROXY_SERVER }}

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Specify your required Node.js version

      # Step 3: Install system dependencies
      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      # Step 4: Install project dependencies
      - name: Install project dependencies
        run: npm install

      # Step 5: Install Playwright tools
      - name: Install Playwright tools
        run: npx playwright install

      # Step 6: Install missing dependencies
      - name: Install missing dependencies
        run: npm install generative-bayesian-network

      # Step 7: Run the Traffic command with xvfb
      - name: Run traffic command with xvfb in parallel
        run: |
          xvfb-run --auto-servernum --server-num=1 --server-args='-screen 0, 1920x1080x24' node traffic.js 1 https://countmytimee.site &
          xvfb-run --auto-servernum --server-num=1 --server-args='-screen 0, 1920x1080x24' node traffic.js 1 https://healthybmi.site &
          xvfb-run --auto-servernum --server-num=1 --server-args='-screen 0, 1920x1080x24' node traffic.js 2 https://telefind.xyz &
          xvfb-run --auto-servernum --server-num=1 --server-args='-screen 0, 1920x1080x24' node traffic.js 1 https://shortinx.xyz &
          wait
